"""Add img field to Wine model

Revision ID: cefb3b44b4f2
Revises: 195597ee1f7f
Create Date: 2024-06-16 19:29:49.684532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefb3b44b4f2'
down_revision = '195597ee1f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=200), nullable=True))
        batch_op.drop_column('size')
        batch_op.drop_column('closure')
        batch_op.drop_column('sub_region')
        batch_op.drop_column('varietals')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('varietals', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sub_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('closure', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
